services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    ports:
      - "8883:8883"
    volumes:
      - ./k8s/base/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./k8s/base/mosquitto.acl:/mosquitto/config/mosquitto.acl:ro
      - ./k8s/base/secrets/mqtt-server.crt:/mosquitto/certs/tls.crt:ro
      - ./k8s/base/secrets/mqtt-server.key:/mosquitto/certs/tls.key:ro
      - ./k8s/base/secrets/mqtt-passwordfile:/mosquitto/auth/passwordfile:ro
      - mosquitto-data:/mosquitto/data

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fleet
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleet -d fleet"]
      interval: 5s
      timeout: 5s
      retries: 10

  telemetry-api:
    build:
      context: ./services/telemetry-api
    env_file:
      - ./k8s/base/secrets/telemetry-api-mqtt.env
    environment:
      DATABASE_URL: postgresql+psycopg://fleet:fleet@postgres:5432/fleet
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 8883
      MQTT_TOPIC: factory/telemetry
      MQTT_TLS_CA_FILE: /etc/mqtt/ca.crt
    volumes:
      - ./k8s/base/secrets/mqtt-ca.crt:/etc/mqtt/ca.crt:ro
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started

  device-sim:
    build:
      context: ./services/device-sim
    env_file:
      - ./k8s/base/secrets/device-sim-mqtt.env
    environment:
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 8883
      MQTT_TOPIC: factory/telemetry
      MQTT_TLS_CA_FILE: /etc/mqtt/ca.crt
    volumes:
      - ./k8s/base/secrets/mqtt-ca.crt:/etc/mqtt/ca.crt:ro
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_started

volumes:
  mosquitto-data:
  postgres-data:
