apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # Values are base64 encoded
  # postgres
  POSTGRES_USER: cG9zdGdyZXM=
  # postgres123
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  # telemetry
  POSTGRES_DB: dGVsZW1ldHJ5
