apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: device-sim
    newName: ghcr.io/silentli/device-sim
    newTag: b295284b4a51728130d42cb1312f81cfe07f4a34
  - name: telemetry-api
    newName: ghcr.io/silentli/telemetry-api
    newTag: b295284b4a51728130d42cb1312f81cfe07f4a34
