apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleet-dashboard
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: telemetry-api
                port:
                  name: http
