listener 8883
allow_anonymous false
password_file /mosquitto/auth/passwordfile
certfile /mosquitto/certs/tls.crt
keyfile /mosquitto/certs/tls.key
persistence true
persistence_location /mosquitto/data/
